import Head from 'next/head';
import Image from 'next/image';
// Component
import Header from '../Components/Header/Header';
import Carousel from '../Components/Carousel/Carousel';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      {/*  FIXME  Head 先不管 */}
      {/* 這之後要搬到 Layout _app.js */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Carousel />
    </div>
  );
}

//  TODO  抓資料先在這裡
